version: '3.7'

services:
  be_support:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: be_support
    image: dedisalam/be_support
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    name: backend
