version: '3.7'

services:
  be_support:
    image: ${OWNER_APP}/${APP_NAME}:latest
    container_name: ${APP_NAME}
    ports:
      - '${PORT}:${PORT}'
    restart: 'unless-stopped'
    networks:
      - production
  

networks:
  production:
    name: production
