# baseURL
@baseURL = https://localhost:7000

###
# Get Categories
GET {{ baseURL }}/customer/categories

###
# Create Category
POST {{ baseURL }}/customer/category
Content-Type: application/json

{
    "name": "example"
}