# baseURL
@baseURL = https://localhost:7000

###
# Get Customers
GET {{ baseURL }}/customers

###
# Create Customers
POST {{ baseURL }}/customer
Content-Type: application/json

{
    "name": "testing"
}