# baseURL
@baseURL = http://localhost:3000

###
# Find All Provinces
GET {{ baseURL }}/region/provinces

###
# Find Province By Id
GET {{ baseURL }}/region/province/1

###
# Create Province
POST {{ baseURL }}/region/province
Content-Type: application/json

{
    "name": "Jawa Barat",
}

###
# Modify Province By Id
PUT {{ baseURL }}/region/province/1
Content-Type: application/json

{
    "name": "Jawa Timur",
}

###
# Delete Province By Id
DELETE {{ baseURL }}/region/province/1
