# baseURL
@baseURL = http://localhost:3000

###
# Find All Subdistricts
GET {{ baseURL }}/region/subdistricts

###
# Find Subdistrict By Id
GET {{ baseURL }}/region/subdistrict/1

###
# Create Subdistrict
POST {{ baseURL }}/region/subdistrict
Content-Type: application/json

{
    "name": "Batununggal",
}

###
# Modify Subdistrict By Id
PUT {{ baseURL }}/region/subdistrict/1
Content-Type: application/json

{
    "name": "Antapani",
}

###
# Delete Subdistrict By Id
DELETE {{ baseURL }}/region/subdistrict/1
