# baseURL
@baseURL = http://localhost:3000

###
# Find All Villages
GET {{ baseURL }}/region/villages

###
# Find Village By Id
GET {{ baseURL }}/region/village/1

###
# Create Village
POST {{ baseURL }}/region/village
Content-Type: application/json

{
    "name": "Kebonwaru",
}

###
# Modify Village By Id
PUT {{ baseURL }}/region/village/1
Content-Type: application/json

{
    "name": "Kacapiring",
}

###
# Delete Village By Id
DELETE {{ baseURL }}/region/village/1
