# baseURL
@baseURL = https://localhost:7000

###
# User Login
POST {{ baseURL }}/admin/user/login
Content-Type: application/json

{
    "email": "example@email.com",
	"password": "password"
}

###
# User Logout
POST {{ baseURL }}/admin/user/logout
Content-Type: application/json
