# baseURL
@baseURL = https://localhost:7000

###
# Find All Users
GET {{ baseURL }}/admin/users

###
# Find User By Id
GET {{ baseURL }}/admin/user/1

###
# Create User
POST {{ baseURL }}/admin/user
Content-Type: application/json

{
    "email": "example@email.com",
	"password": "password"
}

###
# Modify User By Id
PUT {{ baseURL }}/admin/user/1
Content-Type: application/json

{
    "email": "example@email.com",
	"password": "password"
}

###
# Delete User By Id
DELETE {{ baseURL }}/admin/user/1
