version: '3.7'

services:
  be_support_dev:
    container_name: be_support_dev
    image: dedisalam/be_support:dev
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
    networks:
      - development

networks:
  development:
    name: development
