version: '3.7'

services:
  be_support:
    container_name: be_support
    image: dedisalam/be_support:latest
    restart: 'unless-stopped'
    ports:
      - '4000:4000'
    networks:
      - production

networks:
  production:
    name: production
