version: '3.7'

services:
  be_support:
    container_name: be_support
    image: dedisalam/be_support:latest
    restart: 'unless-stopped'
    networks:
      - production

networks:
  production:
    name: production
